# SPDX-License-Identifier: AGPL-3.0-or-later
# The other half of pinning actions to SHAs. Without this, a pin means CI
# keeps running a version nobody revisits.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
